# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_article_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
