# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_article_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='empty', upload_to='/reader/img/'),
            preserve_default=False,
        ),
    ]
