# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20161112_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
