# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='reader.Article'),
        ),
    ]
